// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAspdtBJ2T_U9X1WBgV6eR9BlyMEjEYZZc',
    appId: '1:456211277696:web:df3783a5491e61c34e8365',
    messagingSenderId: '456211277696',
    projectId: 'yahya-portfolio-7bc42',
    authDomain: 'yahya-portfolio-7bc42.firebaseapp.com',
    storageBucket: 'yahya-portfolio-7bc42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoqqK_ylo9dAdJV8J_iaBz2by4kj5SshA',
    appId: '1:456211277696:android:d18dd41eeacb83844e8365',
    messagingSenderId: '456211277696',
    projectId: 'yahya-portfolio-7bc42',
    storageBucket: 'yahya-portfolio-7bc42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-05vQcZ45fHfZH-8eZFgH7jXUXjWXLvg',
    appId: '1:456211277696:ios:be4f0ac046d71c824e8365',
    messagingSenderId: '456211277696',
    projectId: 'yahya-portfolio-7bc42',
    storageBucket: 'yahya-portfolio-7bc42.appspot.com',
    iosBundleId: 'com.muhammadYahya.portfolio',
  );
}
